### ISSUE TITLE
[minor] uglify-js must not already be present in the package.json of the app

### ISSUE THREAD

**Issue by petarov** [alastairparagas/cordova-minify#4]
**uglify-js** must not already be installed/present in the package.json of the app. Otherwise this line fails:

```javascript
var UglifyJS = require('cordova-minify/node_modules/uglify-js');
```

Perhaps useful for the README. ;)

**Comment by alastairparagas** [comment]
@petarov Thank you for the heads up. Will put it on the README.

**Comment by alastairparagas** [comment]
@petarov Fixed in code. [Check it out](https://github.com/alastairparagas/cordova-minify/blob/master/after_prepare/cordova-minify.js#L5-L7).
