### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by piermariacosina** [alastairparagas/cordova-minify#5]
I don't know still if it is a bug 
but the installation succeed with no issue, but I don't see anything that can tell that the module is doing anything during or after the build.

I see the after_prepare js file.

is there something I can do to test if it working?

**Comment by alastairparagas** [comment]
It usually runs whenever you compile your app. It throws a terminal message to notify you when the package is running.

**Comment by webalchemist** [comment]
Have you remembered to make the hooks/afer_prepare/minify.js file executable?
If you don't do this it will fail silently on some platforms.

If you want to check whether it has worked just see if the files under platforms/ios/www (or platforms/android/www) been minified.
