### ISSUE TITLE
npm uninstall leaves the hook behind

### ISSUE THREAD

**Issue by erbridge** [alastairparagas/cordova-minify#7]
It looks like it tries to remove `cordova-minify.js` but the file is called `minify.js`.

**Comment by alastairparagas** [comment]
@erbridge Sorry for the late response. On it.

**Comment by alastairparagas** [comment]
@erbridge It looks like you are using an old version of Cordova Minify. I have checked the install and uninstall scripts and they both reference `cordova-minify.js`.

**Comment by erbridge** [comment]
Actually, it's renamed here: https://github.com/alastairparagas/cordova-minify/blob/master/scripts/install.js#L24

**Comment by alastairparagas** [comment]
@erbridge It's fixed now. It was deleting the wrong file. It is now deleting the right file - https://github.com/alastairparagas/cordova-minify/blob/master/scripts/uninstall.js#L7.
