### ISSUE TITLE
Too long path names on windows

### ISSUE THREAD

**Issue by contactabbas** [alastairparagas/cordova-minify#8]
The node-modules required by cordova-minify has image-min, which has too many dependencies. On windows, this results into a very deep folder structure, which creates a problem while trying to copy the "node-modules" to a different folder. It gives "Source path too long" error when trying to copy the node-modules to a new location.

**Comment by alastairparagas** [comment]
@contactabbas On it. Image-min seems to be a deprecated Node package anyway, so let me work on this.
