### ISSUE TITLE
Not working with Ionic - Failed to instantiate module starter due to: Unknown provider: t

### ISSUE THREAD

**Issue by mladenp** [alastairparagas/cordova-minify#9]
So i tried to use this with Ionic Framework but it gives me an error:
Failed to instantiate module starter due to:
Error: [$injector:unpr] Unknown provider: t
full error: http://pastebin.com/8BdHkk1Q
And as someone else mentioned issue here, you can't remove this module correctly. Because its uninstalling wrong file name cordova-minify.js

**Comment by alastairparagas** [comment]
@mladenp Sorry for the late response, have been somewhat busy. Make sure that your Angular dependencies are safe for minification by using [Angular's minification-safe dependency syntax](https://docs.angularjs.org/tutorial/step_05). That would be my reason as to why your Angular code is not minifying correctly.
